"""
alpaca_paper_trading.py — Free paper trading via Alpaca Markets API.

Reads the unified core-satellite signal (core_satellite_alpha_signal.csv)
generated by core_satellite_alpha.py, and submits orders to Alpaca's free paper
trading environment.  Supports SPY, QQQ, TQQQ core ETFs + stock overlay.
TQQQ allocation is determined by the nested walkforward grid search — when the
winning config has tqqq_weight > 0, the signal includes target_tqqq_weight.

Setup:
    1. Sign up at https://alpaca.markets (instant, free)
    2. Get your paper trading API keys from the dashboard
    3. Set environment variables:
         export ALPACA_API_KEY="your-key"
         export ALPACA_SECRET_KEY="your-secret"
    4. pip install alpaca-trade-api

Usage:
    python3 alpaca_paper_trading.py                  # show current state + plan
    python3 alpaca_paper_trading.py --submit         # actually submit orders
    python3 alpaca_paper_trading.py --status         # just show positions
    python3 alpaca_paper_trading.py --reconcile      # check if pending orders filled
    python3 alpaca_paper_trading.py --force          # skip drift + duplicate checks
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from broker_interface import Broker, Order, Position, Fill
from safe_io import atomic_write_csv, atomic_write_json, configure_console_output
from settings import SIGNAL_DIR
from signal_freshness import (
    extract_signal_weights,
    validate_live_config_match,
    validate_signal_freshness,
    validate_signal_sanity,
)
from alpaca_protection import (
    CORE_PROTECTION_ENABLED,
    CORE_PROTECTION_TICKERS,
    cancel_core_etf_protective_stops,
    repair_core_etf_protective_stops,
)

configure_console_output()

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG — all from environment variables
# ─────────────────────────────────────────────────────────────────────────────

ALPACA_API_KEY = os.environ.get("ALPACA_API_KEY", "").strip()
ALPACA_SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY", "").strip()
# Paper trading base URL (different from live!)
ALPACA_BASE_URL = os.environ.get(
    "ALPACA_BASE_URL", "https://paper-api.alpaca.markets"
).strip()

# Trading parameters
ETF_TICKERS = {"SPY", "QQQ", "TQQQ", "BIL", "IEF", "GLD"}
ETF_DRIFT_THRESHOLD = float(os.environ.get("ALPACA_ETF_DRIFT_THRESHOLD", "0.03"))
OVERLAY_DRIFT_THRESHOLD = float(os.environ.get("ALPACA_OVERLAY_DRIFT_THRESHOLD", "0.01"))
MIN_TRADE_VALUE = float(os.environ.get("ALPACA_MIN_TRADE_VALUE", "25.0"))
MAX_GROSS_EXPOSURE = float(os.environ.get("ALPACA_MAX_GROSS_EXPOSURE", "1.00"))
DEFAULT_MAX_SIGNAL_AGE_HOURS = float(os.environ.get("ALPACA_MAX_SIGNAL_AGE_HOURS", "24.0"))
DEFAULT_MAX_FACTOR_AGE_TRADING_DAYS = int(os.environ.get("ALPACA_MAX_FACTOR_AGE_TRADING_DAYS", "5"))

# ── STOP-LOSS CONFIGURATION ───────────────────────────────────────────────────
# PLAIN ENGLISH: After buying overlay stocks, we place a trailing stop order
# that automatically sells if the stock drops X% from its highest price.
# This protects against catastrophic single-stock losses between rebalances.
# ETFs (SPY, QQQ, TQQQ) do NOT get trailing stops — they're managed by regime
# switching which already reduces exposure during downturns.

TRAILING_STOP_ENABLED = bool(os.environ.get("ALPACA_TRAILING_STOP", "1"))
# Default 8% trailing stop — matches trade_rules.py take_profit_pct as a
# reasonable "let winners run but cut losers" threshold.
TRAILING_STOP_PCT = float(os.environ.get("ALPACA_TRAILING_STOP_PCT", "0.08"))
# Portfolio-level drawdown circuit breaker — if total account drops more than
# this from peak, cancel all pending orders and don't submit new ones.
PORTFOLIO_DRAWDOWN_HALT_PCT = float(os.environ.get("ALPACA_DD_HALT_PCT", "0.12"))
# TQQQ fast circuit breaker — if TQQQ is down more than this from its recent
# N-day high at trade time, skip any TQQQ buy and close any existing TQQQ position.
# This is a pre-trade guard that fires BEFORE the 100-day regime detector catches up.
# Set TQQQ_FAST_DD_THRESHOLD to 0.0 to disable (not recommended for live use).
TQQQ_FAST_DD_THRESHOLD = float(os.environ.get("TQQQ_FAST_DD_THRESHOLD", "-0.15"))
TQQQ_FAST_DD_LOOKBACK_DAYS = int(os.environ.get("TQQQ_FAST_DD_LOOKBACK_DAYS", "5"))

# Signal file path — reads the unified core-satellite signal
# (generated by: python3 core_satellite_alpha.py)
SIGNAL_FILE = Path(SIGNAL_DIR) / "core_satellite_alpha_signal.csv"
LIVE_CONFIG_FILE = Path(SIGNAL_DIR) / "core_satellite_live_configs.json"
# Plan CSV written after orders are computed, even on a dry plan.  Health,
# status, notifications, and the dashboard read this one file.
ORDER_PLAN_FILE = Path(SIGNAL_DIR) / "core_satellite_alpha_orders.csv"
# Paper trading log — tracks all submissions
PAPER_LOG_FILE = Path(SIGNAL_DIR) / "alpaca_paper_log.csv"
# Equity snapshot file — tracks daily account value for gauntlet
EQUITY_FILE = Path(SIGNAL_DIR) / "alpaca_paper_equity.csv"
# PLAIN ENGLISH: Status file lets core_satellite_alpha.py compute
# "sticky" overlay holdings from the same Alpaca account that trades.
STATUS_FILE = Path(SIGNAL_DIR) / "alpaca_daily_status.json"

# Retry config for price fetches
PRICE_RETRY_ATTEMPTS = int(os.environ.get("ALPACA_PRICE_RETRIES", "3"))
PRICE_RETRY_BASE_DELAY = float(os.environ.get("ALPACA_PRICE_RETRY_DELAY", "1.0"))

# Spread guard — skip market orders when bid-ask spread is abnormally wide.
# PLAIN ENGLISH: If a stock's spread is wider than this threshold, a market
# order would fill at a terrible price.  Better to skip it and alert.
# Core ETFs (SPY/QQQ/TQQQ) typically have 0.01-0.05% spreads.
# Overlay stocks typically have 0.05-0.3% spreads.
# Anything above 1% is suspiciously illiquid or halted.
MAX_SPREAD_PCT_ETF = float(os.environ.get("MAX_SPREAD_PCT_ETF", "0.005"))  # 0.5% for ETFs
MAX_SPREAD_PCT_OVERLAY = float(os.environ.get("MAX_SPREAD_PCT_OVERLAY", "0.015"))  # 1.5% for stocks


def _truthy(value: object) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y"}


# ─────────────────────────────────────────────────────────────────────────────
# RETRY HELPER — retries transient broker API failures automatically
# ─────────────────────────────────────────────────────────────────────────────

def _broker_retry(func, *, max_retries: int = 3, base_delay: float = 1.0):
    """Decorator: retry broker method on transient network errors.

    PLAIN ENGLISH: If a broker API call fails with a temporary error (network
    timeout, 5xx server error), wait a moment and try again.  After 3 failures
    in a row, give up and raise the last error.  This prevents a single hiccup
    from killing the entire daily run.
    """
    import functools
    import time as _time

    @functools.wraps(func)
    def wrapper(*args, **kwargs):
        last_exc = None
        for attempt in range(max_retries + 1):
            try:
                return func(*args, **kwargs)
            except Exception as exc:
                last_exc = exc
                exc_str = str(exc).lower()
                # Only retry on transient errors, not auth/validation failures
                is_transient = any(s in exc_str for s in (
                    "timeout", "timed out", "connection", "502", "503",
                    "504", "500", "rate limit", "429", "retry",
                ))
                if not is_transient or attempt >= max_retries:
                    raise
                delay = base_delay * (2 ** attempt)
                _time.sleep(delay)
        raise last_exc  # unreachable but satisfies type checker
    return wrapper


# ─────────────────────────────────────────────────────────────────────────────
# ALPACA BROKER — implements the Broker abstract interface
# ─────────────────────────────────────────────────────────────────────────────

class AlpacaBroker(Broker):
    """
    Alpaca paper trading broker.

    PLAIN ENGLISH: This class talks to Alpaca's free paper trading API.
    It can check your account balance, see what you own, and buy/sell stocks.
    All trades go to the paper (fake money) account — no real money involved.
    """

    def __init__(self):
        # Import here so the rest of the script doesn't crash if alpaca isn't installed
        try:
            from alpaca_trade_api import REST
        except ImportError:
            raise ImportError(
                "alpaca-trade-api not installed. Run: pip install alpaca-trade-api"
            )

        if not ALPACA_API_KEY or not ALPACA_SECRET_KEY:
            raise ValueError(
                "Missing ALPACA_API_KEY or ALPACA_SECRET_KEY environment variables.\n"
                "Sign up free at https://alpaca.markets and set:\n"
                "  export ALPACA_API_KEY='your-key'\n"
                "  export ALPACA_SECRET_KEY='your-secret'"
            )

        self._api = REST(
            key_id=ALPACA_API_KEY,
            secret_key=ALPACA_SECRET_KEY,
            base_url=ALPACA_BASE_URL,
        )
        # Verify connection
        try:
            self._account = self._api.get_account()
        except Exception as e:
            raise ConnectionError(f"Could not connect to Alpaca: {e}")

    @_broker_retry
    def get_equity(self) -> float:
        """Get total account equity (cash + positions market value)."""
        account = self._api.get_account()
        return float(account.equity)

    @_broker_retry
    def get_cash(self) -> float:
        """Get available cash."""
        account = self._api.get_account()
        return float(account.cash)

    @_broker_retry
    def get_positions(self) -> list[Position]:
        """Get all current positions."""
        positions = self._api.list_positions()
        return [
            Position(
                ticker=str(p.symbol),
                quantity=int(float(p.qty)),
                avg_price=float(p.avg_entry_price),
            )
            for p in positions
        ]

    def get_position_map(self) -> dict[str, int]:
        """Get positions as a simple ticker → quantity dict."""
        return {p.ticker: p.quantity for p in self.get_positions()}

    @_broker_retry
    def place_order(self, order: Order) -> str:
        """
        Submit an order to Alpaca.

        PLAIN ENGLISH: Sends a buy or sell order.  Uses market orders by
        default (fills immediately at current price).  For trailing stop
        orders, Alpaca will automatically sell if the stock drops X% from
        its high point after the order is placed.  Returns the order ID
        so we can track it later.
        """
        kwargs = {
            "symbol": order.ticker,
            "qty": int(order.quantity),
            "side": order.side,
            "time_in_force": "gtc",  # trailing stops need GTC (good-til-cancelled)
        }
        if order.client_id:
            kwargs["client_order_id"] = order.client_id

        if order.type == "trailing_stop" and order.trail_percent is not None:
            # PLAIN ENGLISH: A trailing stop follows the stock price UP but
            # triggers a sell if it drops X% from the highest price seen.
            # Example: trail_percent=0.06, stock hits $100 → stop at $94.
            # If stock goes to $110, stop moves up to $103.40 automatically.
            kwargs["type"] = "trailing_stop"
            kwargs["trail_percent"] = str(round(float(order.trail_percent) * 100, 2))
            kwargs["time_in_force"] = "gtc"  # trailing stops must be GTC
        elif order.type == "limit" and order.limit_price is not None:
            kwargs["type"] = "limit"
            kwargs["limit_price"] = round(float(order.limit_price), 2)
            kwargs["time_in_force"] = "day"
        else:
            kwargs["type"] = "market"
            kwargs["time_in_force"] = "day"

        result = self._api.submit_order(**kwargs)
        return str(result.id)

    def cancel_order(self, order_id: str) -> bool:
        """Cancel a pending order."""
        try:
            self._api.cancel_order(order_id)
            return True
        except Exception:
            return False

    def cancel_all_orders(self) -> int:
        """Cancel all open orders. Returns count cancelled."""
        try:
            self._api.cancel_all_orders()
            return 1  # Alpaca doesn't return count
        except Exception:
            return 0

    def recent_fills(self, since_iso: str) -> list[Fill]:
        """Get recently filled orders."""
        try:
            orders = self._api.list_orders(
                status="filled",
                after=since_iso,
                limit=100,
            )
            return [
                Fill(
                    order_id=str(o.id),
                    ticker=str(o.symbol),
                    side=str(o.side),
                    quantity=int(float(o.filled_qty)),
                    price=float(o.filled_avg_price),
                    commission=0.0,  # Alpaca is commission-free
                )
                for o in orders
            ]
        except Exception:
            return []

    def is_market_open(self) -> bool:
        """Check if US market is currently open."""
        clock = self._api.get_clock()
        return bool(clock.is_open)

    def get_spread_pct(self, ticker: str) -> float | None:
        """Get current bid-ask spread as a percentage of midpoint.

        PLAIN ENGLISH: The 'spread' is the gap between what buyers offer (bid)
        and what sellers ask (ask).  A 0.1% spread means you lose 0.1% just by
        entering and exiting.  Wide spreads (>1%) mean the stock is illiquid
        and market orders will get bad fills.

        Returns spread as a fraction (e.g. 0.005 = 0.5%), or None if unavailable.
        """
        try:
            snapshot = self._api.get_snapshot(ticker)
            quote = snapshot.latest_quote
            bid = float(quote.bp) if hasattr(quote, 'bp') else float(quote.bid_price)
            ask = float(quote.ap) if hasattr(quote, 'ap') else float(quote.ask_price)
            if bid > 0 and ask > 0:
                mid = (bid + ask) / 2
                return (ask - bid) / mid
        except Exception:
            pass
        return None

    def get_last_price(self, ticker: str) -> float:
        """
        Get last traded price for a ticker with retry logic.

        PLAIN ENGLISH: Tries to fetch the latest price from Alpaca.  If the
        first attempt fails (network blip, API throttle), it waits and retries
        with exponential backoff (1s, 2s, 4s).  Logs every failure so you
        know when prices are having issues.
        """
        for attempt in range(PRICE_RETRY_ATTEMPTS):
            try:
                quote = self._api.get_latest_trade(ticker)
                return float(quote.price)
            except Exception as e1:
                # Fallback: try snapshot endpoint
                try:
                    snapshot = self._api.get_snapshot(ticker)
                    return float(snapshot.latest_trade.price)
                except Exception as e2:
                    # If not the last attempt, wait and retry
                    if attempt < PRICE_RETRY_ATTEMPTS - 1:
                        delay = PRICE_RETRY_BASE_DELAY * (2 ** attempt)
                        print(f"    ⚠ Price fetch failed for {ticker} "
                              f"(attempt {attempt+1}/{PRICE_RETRY_ATTEMPTS}): {e1} — "
                              f"retrying in {delay:.0f}s...")
                        time.sleep(delay)
                    else:
                        # Final attempt failed — log and return 0
                        print(f"    ✗ Price fetch FAILED for {ticker} after "
                              f"{PRICE_RETRY_ATTEMPTS} attempts: {e1} / {e2}")
        return 0.0


# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL LOADING — reads the unified paper signal file
# ─────────────────────────────────────────────────────────────────────────────

def load_signal() -> pd.Series:
    """
    Load the core-satellite signal file.

    PLAIN ENGLISH: Reads the CSV that tells us what to buy/sell today.
    Checks that the strategy passed all safety gates before allowing trades.
    """
    if not SIGNAL_FILE.exists():
        raise FileNotFoundError(f"Signal file not found: {SIGNAL_FILE}")

    df = pd.read_csv(SIGNAL_FILE)
    if df.empty:
        raise RuntimeError("Signal file is empty")

    row = df.iloc[0]

    # Safety check: only trade if strategy is paper-ready
    if not _truthy(row.get("paper_ready", False)):
        raise RuntimeError(
            f"Strategy is NOT paper-ready. Reason: {row.get('reason', 'unknown')}"
        )
    if not _truthy(row.get("gates_all_pass", False)):
        raise RuntimeError("Strategy gates have not all passed")
    if not _truthy(row.get("medium_risk_review_pass", False)):
        raise RuntimeError(
            "Medium-risk review has not passed. Regenerate the unified signal after "
            "`python3 core_satellite_nested_walkforward.py --strategy core-alpha --publish-live-config`."
        )

    return row


def check_signal_freshness(
    signal: pd.Series,
    *,
    allow_stale_signal: bool = False,
    check_live_config_match: bool = False,
    max_signal_age_hours: float = DEFAULT_MAX_SIGNAL_AGE_HOURS,
    max_factor_age_trading_days: int = DEFAULT_MAX_FACTOR_AGE_TRADING_DAYS,
    now: datetime | None = None,
) -> tuple[bool, list[str]]:
    freshness_ok, freshness_issues = validate_signal_freshness(
        signal,
        max_signal_age_hours=max_signal_age_hours,
        max_factor_age_trading_days=max_factor_age_trading_days,
        now=now,
    )
    # PLAIN ENGLISH: A signal can be fresh by time but still come from the
    # previous approved config.  The broker should only trade the signal that
    # was generated after the current live config was published.
    if check_live_config_match:
        config_ok, config_issues = validate_live_config_match(
            signal,
            live_config_path=LIVE_CONFIG_FILE,
            strategy="core-alpha",
        )
        if not config_ok:
            raise RuntimeError(f"Signal/live config mismatch: {', '.join(config_issues)}")

    if freshness_ok:
        return True, []
    if allow_stale_signal:
        return False, freshness_issues
    raise RuntimeError(f"Stale signal/data: {', '.join(freshness_issues)}")


def parse_target_weights(signal: pd.Series) -> dict[str, float]:
    """
    Extract target portfolio weights from the signal.

    PLAIN ENGLISH: The signal file says "hold 40% SPY, 35% QQQ, 10% AAPL..."
    This function reads those target weights and returns them as a dictionary.
    """
    return extract_signal_weights(signal)


def scale_weights(weights: dict[str, float], max_gross: float) -> dict[str, float]:
    """
    Scale weights down if total gross exposure exceeds the limit.

    PLAIN ENGLISH: If the strategy says to invest 125% of your money (using
    leverage), but you only want to invest 100%, this scales everything down
    proportionally.
    """
    gross = sum(abs(w) for w in weights.values())
    if gross <= max_gross + 1e-9 or gross <= 0:
        return dict(weights)
    scale = max_gross / gross
    return {t: w * scale for t, w in weights.items()}


# ─────────────────────────────────────────────────────────────────────────────
# ORDER GENERATION — compares target weights to current positions
# ─────────────────────────────────────────────────────────────────────────────

def generate_orders(
    broker: AlpacaBroker,
    target_weights: dict[str, float],
    force: bool = False,
) -> list[dict]:
    """
    Compare current positions to targets and generate buy/sell orders.

    PLAIN ENGLISH: Looks at what you currently own, compares it to what
    the strategy wants you to own, and figures out what to buy/sell.
    Only generates orders if the difference ("drift") is big enough to
    matter — avoids tiny trades that cost more than they're worth.
    """
    try:
        equity = float(broker.get_equity())
    except (TypeError, ValueError):
        raise RuntimeError("Invalid broker equity; refusing to generate orders")
    if not np.isfinite(equity) or equity <= 0:
        raise RuntimeError("Invalid broker equity; refusing to generate orders")
    positions = broker.get_position_map()

    # Get current prices for all relevant tickers
    all_tickers = sorted(set(target_weights.keys()) | set(positions.keys()))
    prices: dict[str, float] = {}
    skipped_tickers: list[str] = []
    for ticker in all_tickers:
        px = broker.get_last_price(ticker)
        if np.isfinite(px) and px > 0:
            prices[ticker] = px
        else:
            skipped_tickers.append(ticker)

    # Log any tickers that couldn't get a price
    if skipped_tickers:
        print(f"    ⚠ Skipped {len(skipped_tickers)} tickers (no price): "
              f"{', '.join(skipped_tickers)}")

    orders = []

    for ticker in all_tickers:
        target_w = target_weights.get(ticker, 0.0)
        px = prices.get(ticker, 0.0)
        if px <= 0:
            continue

        # Current weight = (shares × price) / equity
        current_qty = positions.get(ticker, 0)
        current_value = current_qty * px
        current_w = current_value / equity if equity > 0 else 0.0

        # Target shares
        target_value = target_w * equity
        # Round to nearest share to minimize drift from target weight.
        # int() truncates toward zero and systematically under-allocates.
        target_qty = round(target_value / px)

        # Drift = difference between target and current weight
        drift = abs(target_w - current_w)

        # Skip if drift is below threshold (unless forced)
        threshold = ETF_DRIFT_THRESHOLD if ticker in ETF_TICKERS else OVERLAY_DRIFT_THRESHOLD
        if drift < threshold and not force:
            continue

        # How many shares to trade
        delta_qty = target_qty - current_qty
        if delta_qty == 0:
            continue

        # Skip tiny orders
        trade_value = abs(delta_qty * px)
        if trade_value < MIN_TRADE_VALUE:
            continue

        side = "buy" if delta_qty > 0 else "sell"
        orders.append({
            "ticker": ticker,
            "side": side,
            "quantity": abs(delta_qty),
            "price": px,
            "trade_value": trade_value,
            "current_weight": round(current_w, 4),
            "target_weight": round(target_w, 4),
            "drift": round(drift, 4),
            "current_qty": current_qty,
            "target_qty": target_qty,
        })

    # Sort: sells first (free up cash), then buys by size
    orders.sort(key=lambda o: (0 if o["side"] == "sell" else 1, -o["trade_value"]))
    return orders


# ─────────────────────────────────────────────────────────────────────────────
# PAPER TRADE LOG — records every submission for tracking performance
# ─────────────────────────────────────────────────────────────────────────────

def log_submission(orders: list[dict], order_ids: list[str]) -> None:
    """Save a record of submitted orders to the paper log file."""
    rows = []
    now = datetime.now(timezone.utc).isoformat()
    for order, oid in zip(orders, order_ids):
        rows.append({
            "submitted_at": now,
            "order_id": oid,
            "ticker": order["ticker"],
            "side": order["side"],
            "quantity": order["quantity"],
            "price": order["price"],
            "trade_value": order["trade_value"],
            "target_weight": order["target_weight"],
            "fill_status": "pending",
        })

    # Skip the write entirely if no orders were submitted (e.g. every
    # proposed order got blocked by spread guards).  Writing an empty
    # DataFrame produces a 0-byte CSV (no header), which then makes
    # reconcile_orders crash with `EmptyDataError: No columns to parse`.
    # Preserving the prior log keeps reconcile happy with the
    # previously-written orders.
    if not rows:
        print("  No orders submitted — preserving existing log file untouched.")
        return

    df = pd.DataFrame(rows)
    if PAPER_LOG_FILE.exists():
        try:
            existing = pd.read_csv(PAPER_LOG_FILE)
            df = pd.concat([existing, df], ignore_index=True)
        except pd.errors.EmptyDataError:
            # Old run wrote a 0-byte file (pre-fix).  Just overwrite.
            pass
    atomic_write_csv(df, PAPER_LOG_FILE)


def _already_submitted_today() -> bool:
    """
    Check if orders were already submitted today.

    PLAIN ENGLISH: Prevents double-ordering.  If you accidentally run
    --submit twice in one day, the second run will warn you instead of
    placing duplicate trades.
    """
    if not PAPER_LOG_FILE.exists():
        return False
    try:
        log = pd.read_csv(PAPER_LOG_FILE)
        if log.empty:
            return False
        # Check for submissions from today (UTC)
        ts_col = "submitted_at" if "submitted_at" in log.columns else "timestamp"
        if ts_col not in log.columns:
            return False
        dates = pd.to_datetime(log[ts_col], errors="coerce", utc=True)
        today = pd.Timestamp.now(tz="UTC").normalize()
        return bool((dates.dt.normalize() == today).any())
    except Exception:
        return False


# ─────────────────────────────────────────────────────────────────────────────
# EQUITY SNAPSHOT — saves account value for gauntlet tracking
# ─────────────────────────────────────────────────────────────────────────────

def snapshot_equity(broker: AlpacaBroker) -> None:
    """
    Save a snapshot of today's account equity to the tracking CSV.

    PLAIN ENGLISH: The gauntlet needs a history of your account value over
    time to compute Sharpe ratio and max drawdown.  This saves today's
    balance so the gauntlet has data to work with.  Runs automatically
    after every order submission.
    """
    try:
        equity = broker.get_equity()
        cash = broker.get_cash()
    except Exception as e:
        print(f"    ⚠ Could not snapshot equity: {e}")
        return

    now = datetime.now()
    row = {
        "date": now.strftime("%Y-%m-%d"),
        "timestamp": now.strftime("%Y-%m-%d %H:%M:%S"),
        "equity": round(equity, 2),
        "cash": round(cash, 2),
        "invested": round(equity - cash, 2),
    }

    df = pd.DataFrame([row])
    if EQUITY_FILE.exists():
        existing = pd.read_csv(EQUITY_FILE)
        # Don't duplicate same-day entries — keep latest
        existing["date"] = existing["date"].astype(str)
        existing = existing[existing["date"] != row["date"]]
        df = pd.concat([existing, df], ignore_index=True)

    atomic_write_csv(df, EQUITY_FILE)
    print(f"    ✓ Equity snapshot: ${equity:,.2f} → {EQUITY_FILE.name}")


def snapshot_status(broker: AlpacaBroker) -> None:
    """
    Write a JSON status file for Alpaca paper account state.

    PLAIN ENGLISH: The signal generator (core_satellite_alpha.py) reads a
    status file to know what the broker is currently holding — it uses
    this to decide which overlay picks to KEEP across rebalances ("sticky
    holdings").  This function writes the structure that downstream
    health and signal readers use.

    Position values come from Alpaca's API directly (market_value field),
    so quantities/values reflect live broker truth, not local trade log.
    """
    try:
        equity = broker.get_equity()
        cash = broker.get_cash()
        # Use the raw API for market_value — broker.get_positions() returns
        # quantity/avg_price only, not current market value.
        raw_positions = broker._api.list_positions()
    except Exception as e:
        print(f"    ⚠ Could not snapshot status: {e}")
        return

    # Build the status shape downstream readers expect.  Format contract:
    #   positions       : {ticker: share_count}      (dict)
    #   position_values : {ticker: dollar_value}     (dict)
    # Extra detail goes into position_details while positions remains a
    # simple ticker-to-share-count map.
    position_values: dict[str, float] = {}
    positions: dict[str, int] = {}
    position_details: list[dict] = []
    for p in raw_positions:
        try:
            ticker = str(p.symbol).upper()
            qty = int(float(p.qty))
            mv = float(p.market_value)
            positions[ticker] = qty
            position_values[ticker] = round(mv, 2)
            position_details.append({
                "ticker": ticker,
                "quantity": qty,
                "avg_price": float(p.avg_entry_price),
                "market_value": round(mv, 2),
                "unrealized_pl": round(float(p.unrealized_pl), 2),
            })
        except Exception:
            continue

    status = {
        "broker": "alpaca",
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "account_equity": round(float(equity), 2),
        "account_cash": round(float(cash), 2),
        "account_invested": round(float(equity) - float(cash), 2),
        "position_count": len(position_details),
        "positions": positions,
        "position_values": position_values,
        "position_details": position_details,
    }
    atomic_write_json(status, STATUS_FILE)
    print(f"    ✓ Status snapshot: {len(position_details)} positions → {STATUS_FILE.name}")


# ─────────────────────────────────────────────────────────────────────────────
# ORDER RECONCILIATION — check if submitted orders actually filled
# ─────────────────────────────────────────────────────────────────────────────

def reconcile_orders(broker: AlpacaBroker) -> None:
    """
    Query Alpaca for order statuses and update the paper log.

    PLAIN ENGLISH: After you submit orders, this checks with Alpaca to see
    if they actually filled.  Updates the log CSV with the real status
    (filled, cancelled, partially_filled, etc.) so the gauntlet can
    compute accurate fill rates.
    """
    if not PAPER_LOG_FILE.exists():
        print("  No paper log found — nothing to reconcile.")
        return

    # Guard against an empty / corrupted CSV — pandas raises EmptyDataError
    # when the file is 0 bytes (the pre-fix bug used to write this when
    # zero orders survived spread/cost guards).  Also catch generic
    # ParserError so a malformed log never crashes the workflow.
    try:
        log = pd.read_csv(PAPER_LOG_FILE)
    except pd.errors.EmptyDataError:
        print("  Paper log is empty (0 bytes) — nothing to reconcile.")
        return
    except pd.errors.ParserError as exc:
        print(f"  Paper log is malformed ({exc}) — skipping reconcile.")
        return

    if log.empty or "order_id" not in log.columns:
        print("  Paper log is empty or missing order_id column.")
        return

    # Only reconcile orders that are still pending
    if "fill_status" not in log.columns:
        log["fill_status"] = "pending"

    pending_mask = log["fill_status"].astype(str).str.lower().isin(["pending", ""])
    pending = log[pending_mask]

    if pending.empty:
        print("  All orders already reconciled — nothing to update.")
        return

    print(f"  Reconciling {len(pending)} pending orders...")
    updated = 0
    for idx, row in pending.iterrows():
        oid = str(row["order_id"])
        if oid.startswith("ERROR") or not oid:
            log.at[idx, "fill_status"] = "submission_failed"
            updated += 1
            continue
        try:
            order = broker._api.get_order(oid)
            status = str(order.status).lower()
            log.at[idx, "fill_status"] = status
            if hasattr(order, "filled_qty") and order.filled_qty:
                log.at[idx, "filled_qty"] = int(float(order.filled_qty))
            if hasattr(order, "filled_avg_price") and order.filled_avg_price:
                log.at[idx, "filled_avg_price"] = float(order.filled_avg_price)
            updated += 1
            status_icon = "✓" if status == "filled" else "⚠"
            print(f"    {status_icon} {row['ticker']} {row['side']} "
                  f"{int(row['quantity'])} → {status}")
        except Exception as e:
            log.at[idx, "fill_status"] = "query_failed"
            print(f"    ✗ {row['ticker']} order {oid[:12]}... → query failed: {e}")
            updated += 1

    atomic_write_csv(log, PAPER_LOG_FILE)
    print(f"\n  ✓ Reconciled {updated} orders. Log updated → {PAPER_LOG_FILE.name}")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN — command line interface
# ─────────────────────────────────────────────────────────────────────────────

def print_account_status(broker: AlpacaBroker) -> None:
    """Print current account state."""
    equity = broker.get_equity()
    cash = broker.get_cash()
    positions = broker.get_positions()

    print(f"\n{'═'*60}")
    print(f"  ALPACA PAPER TRADING ACCOUNT")
    print(f"{'═'*60}")
    print(f"  Equity:     ${equity:,.2f}")
    print(f"  Cash:       ${cash:,.2f}")
    print(f"  Invested:   ${equity - cash:,.2f}")
    print(f"  Market:     {'OPEN ✓' if broker.is_market_open() else 'CLOSED ✗'}")
    print(f"{'─'*60}")

    if positions:
        print(f"  {'Ticker':<8s} {'Qty':>6s} {'Avg Price':>10s} {'Value':>12s} {'Weight':>8s}")
        print(f"  {'─'*50}")
        for p in sorted(positions, key=lambda x: -x.quantity * x.avg_price):
            value = p.quantity * p.avg_price
            weight = value / equity if equity > 0 else 0
            print(f"  {p.ticker:<8s} {p.quantity:>6d} ${p.avg_price:>9.2f} ${value:>11,.2f} {weight:>7.1%}")
        invested = sum(p.quantity * p.avg_price for p in positions)
        print(f"  {'─'*50}")
        print(f"  {'TOTAL':<8s} {'':>6s} {'':>10s} ${invested:>11,.2f} {invested/equity:>7.1%}")
    else:
        print("  No positions (100% cash)")
    print()


def print_order_plan(orders: list[dict]) -> None:
    """Print the proposed orders before submission."""
    if not orders:
        print("  No orders needed — portfolio is on target.")
        return

    total_buy = sum(o["trade_value"] for o in orders if o["side"] == "buy")
    total_sell = sum(o["trade_value"] for o in orders if o["side"] == "sell")

    print(f"\n  ORDER PLAN ({len(orders)} orders)")
    print(f"  {'─'*55}")
    print(f"  {'Action':<6s} {'Ticker':<8s} {'Qty':>6s} {'Price':>9s} {'Value':>10s} "
          f"{'Current':>8s} {'Target':>8s} {'Drift':>7s}")
    print(f"  {'─'*55}")

    for o in orders:
        action = "BUY" if o["side"] == "buy" else "SELL"
        print(f"  {action:<6s} {o['ticker']:<8s} {o['quantity']:>6d} "
              f"${o['price']:>8.2f} ${o['trade_value']:>9,.2f} "
              f"{o['current_weight']:>7.1%} {o['target_weight']:>7.1%} "
              f"{o['drift']:>6.1%}")

    print(f"  {'─'*55}")
    print(f"  Total buys:  ${total_buy:,.2f}")
    print(f"  Total sells: ${total_sell:,.2f}")
    print(f"  Net flow:    ${total_buy - total_sell:+,.2f}")
    print()


# ─────────────────────────────────────────────────────────────────────────────
# TRAILING STOP-LOSS — protect overlay positions from catastrophic drops
# ─────────────────────────────────────────────────────────────────────────────

def submit_trailing_stops(broker: AlpacaBroker, buy_orders: list[dict]) -> list[str]:
    """
    After buying overlay stocks, submit trailing stop orders for each.

    PLAIN ENGLISH: For every stock we just bought (NOT ETFs), place a
    trailing stop that will automatically sell if the stock drops X% from
    its highest price.  This means:
    - If the stock goes UP, the stop follows it up (locking in gains)
    - If the stock drops X% from its peak, it triggers a sell (cutting loss)

    We only place stops on overlay stocks (individual names), not on ETFs
    like SPY/QQQ/TQQQ which are managed by regime switching.

    Returns list of stop order IDs.
    """
    if not TRAILING_STOP_ENABLED:
        return []

    # Only place stops on non-ETF buys (overlay stock positions)
    overlay_buys = [o for o in buy_orders if o["ticker"] not in ETF_TICKERS and o["side"] == "buy"]
    if not overlay_buys:
        return []

    print(f"\n  Placing trailing stops ({TRAILING_STOP_PCT*100:.0f}%) on {len(overlay_buys)} overlay stocks...")
    stop_ids = []
    for o in overlay_buys:
        try:
            stop_order = Order(
                ticker=o["ticker"],
                side="sell",
                quantity=o["quantity"],
                type="trailing_stop",
                trail_percent=TRAILING_STOP_PCT,
            )
            oid = broker.place_order(stop_order)
            stop_ids.append(oid)
            print(f"    ✓ TRAIL STOP {o['ticker']} qty={o['quantity']} "
                  f"trail={TRAILING_STOP_PCT*100:.0f}% → {oid[:12]}...")
        except Exception as e:
            print(f"    ✗ TRAIL STOP {o['ticker']} FAILED: {e}")
            stop_ids.append(f"ERROR: {e}")

    return stop_ids


def check_portfolio_drawdown(broker: AlpacaBroker) -> tuple[bool, float]:
    """
    Check if the portfolio has hit the drawdown halt threshold.

    PLAIN ENGLISH: Look at the equity history file. If today's account
    value is more than X% below the all-time high, we're in a drawdown
    that's too deep — halt trading until it recovers.

    Returns (is_halted: bool, current_drawdown: float).
    A drawdown of -0.10 means the account is 10% below peak.
    """
    if not EQUITY_FILE.exists():
        return False, 0.0

    try:
        eq = pd.read_csv(EQUITY_FILE)
        if eq.empty or "equity" not in eq.columns:
            return False, 0.0

        peak = float(eq["equity"].max())
        current = broker.get_equity()

        if peak <= 0:
            return False, 0.0

        drawdown = (current - peak) / peak  # negative number when in drawdown

        if drawdown < -PORTFOLIO_DRAWDOWN_HALT_PCT:
            return True, drawdown
        return False, drawdown
    except Exception:
        return False, 0.0


def _tqqq_pre_trade_check(broker: AlpacaBroker) -> tuple[bool, float]:
    """
    Check whether TQQQ is in a fast drawdown that warrants blocking the buy.

    PLAIN ENGLISH: Before placing any TQQQ buy order, we check whether TQQQ
    has already fallen a lot from its recent high (default: 15% from 5-day high).
    If it has, we skip the TQQQ buy.  This fires much faster than the regime
    detector (which needs ~20 trading days) and prevents buying into a crash.

    Returns (is_safe, drawdown_from_high).
    is_safe=True means it is OK to buy TQQQ.
    is_safe=False means TQQQ is in fast drawdown — skip the buy.
    """
    if TQQQ_FAST_DD_THRESHOLD >= 0.0:
        return True, 0.0  # disabled
    try:
        import yfinance as yf
        hist = yf.download("TQQQ", period=f"{TQQQ_FAST_DD_LOOKBACK_DAYS + 2}d",
                           interval="1d", progress=False, auto_adjust=True)
        if hist.empty or "Close" not in hist.columns:
            return True, 0.0
        closes = hist["Close"].dropna()
        if len(closes) < 2:
            return True, 0.0
        window = closes.iloc[-TQQQ_FAST_DD_LOOKBACK_DAYS:]
        recent_high = float(window.max())
        current = float(closes.iloc[-1])
        drawdown = (current - recent_high) / recent_high if recent_high > 0 else 0.0
        return drawdown > TQQQ_FAST_DD_THRESHOLD, drawdown
    except Exception as e:
        print(f"  ⚠ TQQQ pre-trade check failed (allowing buy): {e}")
        return True, 0.0


# Sentinel file written when emergency liquidation fires — prevents re-triggering
# on subsequent runs.  Auto-clears on the next calendar day if drawdown has
# recovered past half the halt threshold (e.g. from -12% back to -6%).
_HALT_SENTINEL_FILE = Path(SIGNAL_DIR) / "alpaca_halt_active.txt"

# Recovery threshold: auto-clear the halt sentinel when drawdown improves
# past this fraction of the halt threshold.  0.5 = recover to half the
# halt level (e.g. if halt is -12%, auto-clear at -6%).
_HALT_RECOVERY_RATIO = 0.5


def _maybe_auto_clear_halt(broker: AlpacaBroker) -> bool:
    """Auto-clear the halt sentinel if drawdown has recovered sufficiently.

    PLAIN ENGLISH: After an emergency liquidation, trading is halted by a
    sentinel file.  Previously you had to manually delete this file.  Now
    we auto-clear it the NEXT DAY if the account's drawdown has improved
    to less than half the halt threshold.

    Example: halt threshold = -12%.  Emergency liquidation fires at -13%.
    Next day, account is at -5% drawdown (recovered).  Since -5% is better
    than -6% (= 12% × 0.5), the sentinel is auto-cleared and trading resumes.

    Returns True if the sentinel was cleared, False otherwise.
    """
    if not _HALT_SENTINEL_FILE.exists():
        return False

    # Only auto-clear if at least one calendar day has passed since the halt.
    # This prevents clearing the same day the halt fired — gives you time
    # to review what happened.
    try:
        sentinel_text = _HALT_SENTINEL_FILE.read_text(encoding="utf-8", errors="replace")
        # Parse the timestamp from the first line: "Emergency liquidation triggered at 2026-05-14T..."
        ts_str = sentinel_text.split("at ")[-1].split("\n")[0].strip()
        halt_time = datetime.fromisoformat(ts_str)
        if (datetime.now() - halt_time).days < 1:
            return False  # same day — don't auto-clear yet
    except Exception:
        pass  # if we can't parse the timestamp, proceed with recovery check

    # Check current drawdown
    _, current_dd = check_portfolio_drawdown(broker)
    recovery_threshold = -PORTFOLIO_DRAWDOWN_HALT_PCT * _HALT_RECOVERY_RATIO

    if current_dd > recovery_threshold:
        # Drawdown has recovered past half the halt level — safe to resume
        _HALT_SENTINEL_FILE.unlink(missing_ok=True)
        print(f"  ✓ Halt auto-cleared: drawdown recovered to {current_dd*100:.1f}% "
              f"(threshold: {recovery_threshold*100:.1f}%)")
        return True
    else:
        print(f"  ⚠ Halt still active: drawdown at {current_dd*100:.1f}% "
              f"(need better than {recovery_threshold*100:.1f}% to auto-clear)")
        return False


def _emergency_liquidate(broker: AlpacaBroker) -> None:
    """
    Cancel all open orders and close all positions via market sells.

    PLAIN ENGLISH: When the portfolio drawdown crosses the halt threshold, we
    don't just stop NEW orders — we also close everything we already hold.
    This prevents continuing to bleed through an existing position while the
    account keeps dropping.  A sentinel file is written so this function only
    fires ONCE per halt event; the user must manually delete
    signals/alpaca_halt_active.txt to re-enable trading after reviewing.
    """
    if _HALT_SENTINEL_FILE.exists():
        print(f"  ⚠ Emergency liquidation already fired this halt event "
              f"(sentinel: {_HALT_SENTINEL_FILE}). Skipping re-trigger.")
        return

    print("  🚨 EMERGENCY LIQUIDATION — cancelling all orders and closing all positions...")

    cancelled = broker.cancel_all_orders()
    print(f"    ✓ Cancelled pending orders (Alpaca reports: {cancelled})")

    positions = broker.get_positions()
    if not positions:
        print("    ✓ No open positions to close.")
    else:
        for pos in positions:
            try:
                order = Order(
                    ticker=pos.ticker,
                    side="sell",
                    quantity=pos.quantity,
                    type="market",
                )
                oid = broker.place_order(order)
                print(f"    ✓ CLOSE {pos.quantity} {pos.ticker} → {oid[:12]}...")
            except Exception as e:
                print(f"    ✗ CLOSE {pos.ticker} FAILED: {e}")

    # Write sentinel so this doesn't re-trigger on the next run
    _HALT_SENTINEL_FILE.write_text(
        f"Emergency liquidation triggered at {datetime.now().isoformat()}\n"
        f"Delete this file to re-enable trading after reviewing the halt.\n"
    )
    print(f"  ✓ Sentinel written: {_HALT_SENTINEL_FILE}")


def main():
    parser = argparse.ArgumentParser(
        description="Alpaca paper trading for unified core-satellite strategy"
    )
    parser.add_argument("--submit", action="store_true",
                        help="Actually submit orders (default: just show plan)")
    parser.add_argument("--status", action="store_true",
                        help="Just show account status, no order planning")
    parser.add_argument("--reconcile", action="store_true",
                        help="Check if pending orders filled and update log")
    parser.add_argument("--force", action="store_true",
                        help="Skip drift thresholds AND duplicate-day check")
    parser.add_argument("--market-order", action="store_true", default=True,
                        help="Use market orders (default)")
    parser.add_argument("--allow-stale-signal", action="store_true",
                        help="Allow order planning/submission even if signal freshness checks fail")
    parser.add_argument("--max-signal-age-hours", type=float, default=DEFAULT_MAX_SIGNAL_AGE_HOURS,
                        help="Block submit if predicted_at is older than this many hours")
    parser.add_argument("--max-factor-age-trading-days", type=int, default=DEFAULT_MAX_FACTOR_AGE_TRADING_DAYS,
                        help="Block submit if latest_factor_date is older than this many trading days")
    args = parser.parse_args()

    # ── Connect to Alpaca ───────────────────────────────────────────────
    try:
        broker = AlpacaBroker()
        print("  ✓ Connected to Alpaca paper trading")
    except ImportError as e:
        print(f"  ✗ {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"  ✗ {e}")
        sys.exit(1)
    except ConnectionError as e:
        print(f"  ✗ {e}")
        sys.exit(1)

    # ── Show account status ─────────────────────────────────────────────
    print_account_status(broker)

    if args.status:
        return

    # ── Reconcile mode: check fill statuses of pending orders ──────────
    if args.reconcile:
        reconcile_orders(broker)
        # Refresh status snapshot too — reconcile may have updated positions
        # via filled orders, and we want the signal to see the new state on
        # tomorrow's run.
        snapshot_status(broker)
        return

    # ── Load strategy signal ────────────────────────────────────────────
    try:
        signal = load_signal()
        print(f"  ✓ Signal loaded (predicted_at: {signal.get('predicted_at', 'unknown')})")
        print(f"    Strategy: {signal.get('paper_signal_type', 'unknown')}")
        print(f"    Regime:   {signal.get('current_regime', 'unknown')}")
        print(f"    Gross:    {signal.get('gross_exposure', 'unknown')}")
    except (FileNotFoundError, RuntimeError) as e:
        print(f"  ✗ {e}")
        sys.exit(1)

    try:
        freshness_ok, freshness_issues = check_signal_freshness(
            signal,
            allow_stale_signal=bool(args.allow_stale_signal),
            check_live_config_match=True,
            max_signal_age_hours=float(args.max_signal_age_hours),
            max_factor_age_trading_days=int(args.max_factor_age_trading_days),
        )
        if not freshness_ok:
            print(f"  ⚠ Stale signal/data allowed by --allow-stale-signal: {', '.join(freshness_issues)}")
    except RuntimeError as e:
        print(f"  ✗ {e}")
        sys.exit(1)

    # ── Signal sanity check — catch broken signals before they become orders ──
    sanity_ok, sanity_issues = validate_signal_sanity(signal)
    if not sanity_ok:
        print(f"  ⚠ Signal sanity issues: {', '.join(sanity_issues)}")
        try:
            from notifications import send_alert
            send_alert(
                f"Signal sanity check FAILED:\n" + "\n".join(f"• {i}" for i in sanity_issues),
                title="Signal Sanity",
                priority="critical",
            )
        except Exception:
            pass
        if not getattr(args, 'force', False):
            print(f"  ✗ Aborting order submission. Use --force to override.")
            sys.exit(1)

    # ── Parse and scale target weights ──────────────────────────────────
    raw_weights = parse_target_weights(signal)
    target_weights = scale_weights(raw_weights, MAX_GROSS_EXPOSURE)

    raw_gross = sum(abs(w) for w in raw_weights.values())
    scaled_gross = sum(abs(w) for w in target_weights.values())
    if abs(raw_gross - scaled_gross) > 0.01:
        print(f"    Scaled {raw_gross:.2f}x → {scaled_gross:.2f}x "
              f"(max gross = {MAX_GROSS_EXPOSURE:.2f}x)")

    print(f"\n  TARGET ALLOCATION")
    print(f"  {'─'*40}")
    for ticker, w in sorted(target_weights.items(), key=lambda x: -abs(x[1])):
        label = "ETF" if ticker in ETF_TICKERS else "Stock"
        print(f"  {ticker:<8s} {w:>7.1%}  ({label})")
    print(f"  {'─'*40}")
    print(f"  Gross exposure: {scaled_gross:.2%}")

    # ── Generate orders ─────────────────────────────────────────────────
    print("\n  Comparing to current positions...")
    orders = generate_orders(broker, target_weights, force=args.force)
    print_order_plan(orders)

    # ── Persist the order plan ──────────────────────────────────────────
    # paper_health, notifications, status, and the
    # dashboard all read signals/core_satellite_alpha_orders.csv to
    # display "what we plan to do today".  Always write — even when
    # orders is empty — so a no-rebalance day produces a header-only
    # CSV instead of leaving yesterday's plan in place.
    try:
        import pandas as _pd
        atomic_write_csv(_pd.DataFrame(orders), ORDER_PLAN_FILE)
        if orders:
            print(f"  Saved order plan -> {ORDER_PLAN_FILE.name} ({len(orders)} rows)")
        else:
            print(f"  Saved empty order plan -> {ORDER_PLAN_FILE.name} (no rebalance today)")
    except Exception as _exc:
        # Plan persistence is informational — don't block submission if
        # the write fails (disk full, permissions, etc.).
        print(f"  ⚠ Could not write order plan: {_exc}")

    if not orders:
        if args.submit and CORE_PROTECTION_ENABLED:
            print("  Checking core ETF protective stops...")
            repair_core_etf_protective_stops(
                broker,
                tickers=CORE_PROTECTION_TICKERS,
                logger=lambda msg: print(f"    {msg}"),
            )
        return

    # ── Submit orders ───────────────────────────────────────────────────
    if not args.submit:
        print("  ⚠  DRY RUN — orders NOT submitted. Use --submit to execute.")
        return

    # ── Auto-clear halt if drawdown has recovered ──────────────────────
    # PLAIN ENGLISH: If we halted trading yesterday because of a big
    # drawdown, check if the account has recovered enough to resume.
    # The sentinel auto-clears the next day if drawdown improved to
    # less than half the halt threshold.
    _maybe_auto_clear_halt(broker)

    # ── Portfolio drawdown halt check ──────────────────────────────────
    # PLAIN ENGLISH: If the portfolio has dropped too much from its peak,
    # refuse to submit new orders.  This prevents throwing good money after
    # bad during a severe downturn.  The halt lifts when equity recovers.
    halted, current_dd = check_portfolio_drawdown(broker)
    if halted and not args.force:
        print(f"  🛑 PORTFOLIO DRAWDOWN HALT: account is {current_dd*100:.1f}% below peak")
        print(f"     Threshold: {PORTFOLIO_DRAWDOWN_HALT_PCT*100:.0f}%")
        print(f"     No new orders until drawdown recovers. Use --force to override.")
        _emergency_liquidate(broker)
        return
    elif current_dd < -0.05:
        # Warn if drawdown is notable but not halting
        print(f"  ⚠  Portfolio drawdown: {current_dd*100:.1f}% from peak "
              f"(halt at {PORTFOLIO_DRAWDOWN_HALT_PCT*100:.0f}%)")

    # Duplicate submission check — prevents running --submit twice in one day
    if _already_submitted_today() and not args.force:
        print("  ⚠  Orders already submitted today. Use --force to override.")
        print(f"     Check log: {PAPER_LOG_FILE}")
        return

    if not broker.is_market_open():
        print("  ⚠  Market is CLOSED. Orders will queue for next open.")
        # PLAIN ENGLISH: When this script runs interactively (you typed the
        # command), we ask before submitting — closed market means weird
        # spreads and night-time fills.  But in CI/cron there's no human
        # at the keyboard, so we auto-proceed (queueing for next open is
        # the desired behavior).  --force overrides either way.
        if args.force:
            print("  --force flag set — proceeding anyway.")
        elif sys.stdin.isatty():
            resp = input("  Continue anyway? [y/N]: ").strip().lower()
            if resp != "y":
                print("  Aborted.")
                return
        else:
            print("  Non-interactive mode — auto-proceeding (orders will queue).")

    # ── Core ETF protective stops — clear before rebalance ───────────────
    # PLAIN ENGLISH: Broker-side trailing stops reserve shares. If we are
    # about to rebalance SPY/QQQ/TQQQ, those old sell stops can block the new
    # sell orders. We cancel only the affected ETF stops here, then repair the
    # protection after orders are submitted/reconciled.
    core_order_tickers = {
        str(o["ticker"]).upper()
        for o in orders
        if str(o["ticker"]).upper() in CORE_PROTECTION_TICKERS
    }
    if CORE_PROTECTION_ENABLED and core_order_tickers:
        print(f"  Clearing core ETF protective stops before rebalance: {', '.join(sorted(core_order_tickers))}")
        protection_cancels = cancel_core_etf_protective_stops(
            broker,
            tickers=core_order_tickers,
            logger=lambda msg: print(f"    {msg}"),
        )
        if any(row.get("status") == "failed" for row in protection_cancels):
            print("  ✗ Could not cancel all affected core ETF protective stops. Aborting rebalance.")
            print("     Existing stops may reserve shares and cause sell orders to fail.")
            return

    # ── TQQQ fast circuit breaker — pre-trade check ───────────────────────
    # PLAIN ENGLISH: Before submitting any TQQQ buy, verify that TQQQ hasn't
    # already crashed more than TQQQ_FAST_DD_THRESHOLD from its recent high.
    # If it has, remove TQQQ buy orders from the list and close any existing
    # TQQQ position.  This is the live-trading equivalent of the signal-time
    # drawdown check.
    tqqq_buys = [o for o in orders if o["ticker"] == "TQQQ" and o["side"] == "buy"]
    if tqqq_buys:
        tqqq_safe, tqqq_dd = _tqqq_pre_trade_check(broker)
        if not tqqq_safe:
            print(f"  🛑 TQQQ fast circuit breaker: {tqqq_dd*100:.1f}% drawdown from "
                  f"{TQQQ_FAST_DD_LOOKBACK_DAYS}-day high (threshold {TQQQ_FAST_DD_THRESHOLD*100:.0f}%).")
            print(f"     Removing TQQQ buy orders and closing any existing TQQQ position.")
            orders = [o for o in orders if not (o["ticker"] == "TQQQ" and o["side"] == "buy")]
            # Close existing TQQQ position if held
            tqqq_pos = broker.get_position_map().get("TQQQ", 0)
            if tqqq_pos > 0:
                try:
                    close_order = Order(ticker="TQQQ", side="sell",
                                        quantity=tqqq_pos, type="market")
                    broker.place_order(close_order)
                    print(f"    ✓ Closed {tqqq_pos} TQQQ shares (circuit breaker exit).")
                except Exception as e:
                    print(f"    ✗ TQQQ close FAILED: {e}")
        else:
            if tqqq_dd < -0.08:
                print(f"  ⚠ TQQQ is {tqqq_dd*100:.1f}% from {TQQQ_FAST_DD_LOOKBACK_DAYS}-day high "
                      f"(circuit breaker threshold {TQQQ_FAST_DD_THRESHOLD*100:.0f}% — still OK).")

    # ── Spread sanity check: skip orders on abnormally wide spreads ──────
    # PLAIN ENGLISH: Before submitting, check the bid-ask spread for each ticker.
    # If the spread is wider than our threshold (e.g. >1.5% for stocks), the market
    # order would fill at a terrible price.  Skip it and log a warning instead.
    _spread_blocked: list[str] = []
    for o in orders:
        ticker = o["ticker"]
        spread = broker.get_spread_pct(ticker)
        threshold = MAX_SPREAD_PCT_ETF if ticker in ETF_TICKERS else MAX_SPREAD_PCT_OVERLAY
        if spread is not None and spread > threshold:
            _spread_blocked.append(ticker)
            print(f"    ⚠ SPREAD BLOCK: {ticker} spread={spread*100:.2f}% "
                  f"(threshold={threshold*100:.1f}%) — skipping order")
    if _spread_blocked:
        orders = [o for o in orders if o["ticker"] not in _spread_blocked]
        try:
            from notifications import send_alert
            send_alert(
                f"Spread guard blocked {len(_spread_blocked)} orders: "
                f"{', '.join(_spread_blocked)}",
                title="Spread Guard",
                priority="warning",
            )
        except Exception:
            pass

    print(f"\n  Submitting {len(orders)} orders...")
    order_ids = []
    # Use today's date as part of a deterministic client_order_id so that
    # network retries cannot double-submit the same logical order.
    _today_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    for o in orders:
        try:
            # Deterministic ID: date_ticker_side_qty — Alpaca rejects duplicates
            _idempotency_key = f"{_today_str}_{o['ticker']}_{o['side']}_{o['quantity']}"
            order = Order(
                ticker=o["ticker"],
                side=o["side"],
                quantity=o["quantity"],
                type="market",
                client_id=_idempotency_key,
            )
            oid = broker.place_order(order)
            order_ids.append(oid)
            print(f"    ✓ {o['side'].upper()} {o['quantity']} {o['ticker']} "
                  f"→ order_id={oid[:12]}...")
        except Exception as e:
            order_ids.append(f"ERROR: {e}")
            print(f"    ✗ {o['side'].upper()} {o['quantity']} {o['ticker']} "
                  f"FAILED: {e}")

    # ── Log the submission ──────────────────────────────────────────────
    log_submission(orders, order_ids)
    print(f"\n  ✓ {len(orders)} orders submitted. Log saved → {PAPER_LOG_FILE}")

    # ── Submit trailing stop-loss orders for overlay stocks ────────────
    # PLAIN ENGLISH: After buying individual stocks, place a trailing stop
    # that will sell automatically if the stock drops 8% from its high.
    # This limits downside on single-name positions between rebalances.
    # ETFs are NOT protected by stops (regime switching handles that).
    stop_ids = submit_trailing_stops(broker, orders)
    if stop_ids:
        successful_stops = [s for s in stop_ids if not str(s).startswith("ERROR")]
        print(f"  ✓ {len(successful_stops)}/{len(stop_ids)} trailing stops placed")

    # ── Auto-snapshot equity for gauntlet tracking ─────────────────────
    # PLAIN ENGLISH: Saves today's account value so the gauntlet can
    # compute your Sharpe ratio and drawdown over time.  Happens
    # automatically — no need to run a separate command.
    snapshot_equity(broker)
    # ── Auto-snapshot Alpaca status (positions + equity) for signal ────
    # PLAIN ENGLISH: The signal generator reads this file to decide which
    # overlay tickers to KEEP across rebalances (sticky holdings).  Must
    # reflect what Alpaca actually holds.
    snapshot_status(broker)

    # ── Durable core ETF protection ─────────────────────────────────────
    # PLAIN ENGLISH: The local guard only works while this laptop is awake.
    # These Alpaca-side trailing stops keep basic ETF protection alive even
    # when the laptop sleeps or is offline.
    if CORE_PROTECTION_ENABLED:
        print("  Repairing core ETF protective stops...")
        repair_core_etf_protective_stops(
            broker,
            tickers=CORE_PROTECTION_TICKERS,
            logger=lambda msg: print(f"    {msg}"),
        )

    print(f"    Check fills: python3 alpaca_paper_trading.py --reconcile")


if __name__ == "__main__":
    main()
