"""
alpaca_paper_trading.py — Free paper trading via Alpaca Markets API.

Reads the TQQQ-enhanced signal (core_satellite_tqqq_signal.csv) generated by
core_satellite_tqqq.py --signal, and submits orders to Alpaca's free paper
trading environment.  Supports SPY, QQQ, TQQQ core ETFs + stock overlay.

Setup:
    1. Sign up at https://alpaca.markets (instant, free)
    2. Get your paper trading API keys from the dashboard
    3. Set environment variables:
         export ALPACA_API_KEY="your-key"
         export ALPACA_SECRET_KEY="your-secret"
    4. pip install alpaca-trade-api

Usage:
    python3 alpaca_paper_trading.py                  # show current state + plan
    python3 alpaca_paper_trading.py --submit         # actually submit orders
    python3 alpaca_paper_trading.py --status         # just show positions
    python3 alpaca_paper_trading.py --reconcile      # check if pending orders filled
    python3 alpaca_paper_trading.py --force          # skip drift + duplicate checks
"""
from __future__ import annotations

import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from broker_interface import Broker, Order, Position, Fill
from settings import SIGNAL_DIR

# ─────────────────────────────────────────────────────────────────────────────
# CONFIG — all from environment variables
# ─────────────────────────────────────────────────────────────────────────────

ALPACA_API_KEY = os.environ.get("ALPACA_API_KEY", "").strip()
ALPACA_SECRET_KEY = os.environ.get("ALPACA_SECRET_KEY", "").strip()
# Paper trading base URL (different from live!)
ALPACA_BASE_URL = os.environ.get(
    "ALPACA_BASE_URL", "https://paper-api.alpaca.markets"
).strip()

# Trading parameters
ETF_TICKERS = {"SPY", "QQQ", "TQQQ", "BIL", "IEF", "GLD"}
ETF_DRIFT_THRESHOLD = float(os.environ.get("ALPACA_ETF_DRIFT_THRESHOLD", "0.03"))
OVERLAY_DRIFT_THRESHOLD = float(os.environ.get("ALPACA_OVERLAY_DRIFT_THRESHOLD", "0.01"))
MIN_TRADE_VALUE = float(os.environ.get("ALPACA_MIN_TRADE_VALUE", "25.0"))
MAX_GROSS_EXPOSURE = float(os.environ.get("ALPACA_MAX_GROSS_EXPOSURE", "1.00"))

# Signal file path — reads TQQQ-enhanced signal by default
# (generated by: python core_satellite_tqqq.py --signal)
SIGNAL_FILE = Path(SIGNAL_DIR) / "core_satellite_tqqq_signal.csv"
# Paper trading log — tracks all submissions
PAPER_LOG_FILE = Path(SIGNAL_DIR) / "alpaca_paper_log.csv"
# Equity snapshot file — tracks daily account value for gauntlet
EQUITY_FILE = Path(SIGNAL_DIR) / "alpaca_paper_equity.csv"

# Retry config for price fetches
PRICE_RETRY_ATTEMPTS = int(os.environ.get("ALPACA_PRICE_RETRIES", "3"))
PRICE_RETRY_BASE_DELAY = float(os.environ.get("ALPACA_PRICE_RETRY_DELAY", "1.0"))


# ─────────────────────────────────────────────────────────────────────────────
# ALPACA BROKER — implements the Broker abstract interface
# ─────────────────────────────────────────────────────────────────────────────

class AlpacaBroker(Broker):
    """
    Alpaca paper trading broker.

    PLAIN ENGLISH: This class talks to Alpaca's free paper trading API.
    It can check your account balance, see what you own, and buy/sell stocks.
    All trades go to the paper (fake money) account — no real money involved.
    """

    def __init__(self):
        # Import here so the rest of the script doesn't crash if alpaca isn't installed
        try:
            from alpaca_trade_api import REST
        except ImportError:
            raise ImportError(
                "alpaca-trade-api not installed. Run: pip install alpaca-trade-api"
            )

        if not ALPACA_API_KEY or not ALPACA_SECRET_KEY:
            raise ValueError(
                "Missing ALPACA_API_KEY or ALPACA_SECRET_KEY environment variables.\n"
                "Sign up free at https://alpaca.markets and set:\n"
                "  export ALPACA_API_KEY='your-key'\n"
                "  export ALPACA_SECRET_KEY='your-secret'"
            )

        self._api = REST(
            key_id=ALPACA_API_KEY,
            secret_key=ALPACA_SECRET_KEY,
            base_url=ALPACA_BASE_URL,
        )
        # Verify connection
        try:
            self._account = self._api.get_account()
        except Exception as e:
            raise ConnectionError(f"Could not connect to Alpaca: {e}")

    def get_equity(self) -> float:
        """Get total account equity (cash + positions market value)."""
        account = self._api.get_account()
        return float(account.equity)

    def get_cash(self) -> float:
        """Get available cash."""
        account = self._api.get_account()
        return float(account.cash)

    def get_positions(self) -> list[Position]:
        """Get all current positions."""
        positions = self._api.list_positions()
        return [
            Position(
                ticker=str(p.symbol),
                quantity=int(float(p.qty)),
                avg_price=float(p.avg_entry_price),
            )
            for p in positions
        ]

    def get_position_map(self) -> dict[str, int]:
        """Get positions as a simple ticker → quantity dict."""
        return {p.ticker: p.quantity for p in self.get_positions()}

    def place_order(self, order: Order) -> str:
        """
        Submit an order to Alpaca.

        PLAIN ENGLISH: Sends a buy or sell order.  Uses market orders by
        default (fills immediately at current price).  Returns the order ID
        so we can track it later.
        """
        kwargs = {
            "symbol": order.ticker,
            "qty": int(order.quantity),
            "side": order.side,
            "time_in_force": "day",  # order expires end of day if not filled
        }

        if order.type == "limit" and order.limit_price is not None:
            kwargs["type"] = "limit"
            kwargs["limit_price"] = round(float(order.limit_price), 2)
        else:
            kwargs["type"] = "market"

        result = self._api.submit_order(**kwargs)
        return str(result.id)

    def cancel_order(self, order_id: str) -> bool:
        """Cancel a pending order."""
        try:
            self._api.cancel_order(order_id)
            return True
        except Exception:
            return False

    def cancel_all_orders(self) -> int:
        """Cancel all open orders. Returns count cancelled."""
        try:
            self._api.cancel_all_orders()
            return 1  # Alpaca doesn't return count
        except Exception:
            return 0

    def recent_fills(self, since_iso: str) -> list[Fill]:
        """Get recently filled orders."""
        try:
            orders = self._api.list_orders(
                status="filled",
                after=since_iso,
                limit=100,
            )
            return [
                Fill(
                    order_id=str(o.id),
                    ticker=str(o.symbol),
                    side=str(o.side),
                    quantity=int(float(o.filled_qty)),
                    price=float(o.filled_avg_price),
                    commission=0.0,  # Alpaca is commission-free
                )
                for o in orders
            ]
        except Exception:
            return []

    def is_market_open(self) -> bool:
        """Check if US market is currently open."""
        clock = self._api.get_clock()
        return bool(clock.is_open)

    def get_last_price(self, ticker: str) -> float:
        """
        Get last traded price for a ticker with retry logic.

        PLAIN ENGLISH: Tries to fetch the latest price from Alpaca.  If the
        first attempt fails (network blip, API throttle), it waits and retries
        with exponential backoff (1s, 2s, 4s).  Logs every failure so you
        know when prices are having issues.
        """
        for attempt in range(PRICE_RETRY_ATTEMPTS):
            try:
                quote = self._api.get_latest_trade(ticker)
                return float(quote.price)
            except Exception as e1:
                # Fallback: try snapshot endpoint
                try:
                    snapshot = self._api.get_snapshot(ticker)
                    return float(snapshot.latest_trade.price)
                except Exception as e2:
                    # If not the last attempt, wait and retry
                    if attempt < PRICE_RETRY_ATTEMPTS - 1:
                        delay = PRICE_RETRY_BASE_DELAY * (2 ** attempt)
                        print(f"    ⚠ Price fetch failed for {ticker} "
                              f"(attempt {attempt+1}/{PRICE_RETRY_ATTEMPTS}): {e1} — "
                              f"retrying in {delay:.0f}s...")
                        time.sleep(delay)
                    else:
                        # Final attempt failed — log and return 0
                        print(f"    ✗ Price fetch FAILED for {ticker} after "
                              f"{PRICE_RETRY_ATTEMPTS} attempts: {e1} / {e2}")
        return 0.0


# ─────────────────────────────────────────────────────────────────────────────
# SIGNAL LOADING — reads the same signal file as moomoo_paper_trading.py
# ─────────────────────────────────────────────────────────────────────────────

def load_signal() -> pd.Series:
    """
    Load the core-satellite signal file.

    PLAIN ENGLISH: Reads the CSV that tells us what to buy/sell today.
    Checks that the strategy passed all safety gates before allowing trades.
    """
    if not SIGNAL_FILE.exists():
        raise FileNotFoundError(f"Signal file not found: {SIGNAL_FILE}")

    df = pd.read_csv(SIGNAL_FILE)
    if df.empty:
        raise RuntimeError("Signal file is empty")

    row = df.iloc[0]

    # Safety check: only trade if strategy is paper-ready
    if not bool(row.get("paper_ready", False)):
        raise RuntimeError(
            f"Strategy is NOT paper-ready. Reason: {row.get('reason', 'unknown')}"
        )
    if not bool(row.get("gates_all_pass", False)):
        raise RuntimeError("Strategy gates have not all passed")

    return row


def parse_target_weights(signal: pd.Series) -> dict[str, float]:
    """
    Extract target portfolio weights from the signal.

    PLAIN ENGLISH: The signal file says "hold 40% SPY, 35% QQQ, 10% AAPL..."
    This function reads those target weights and returns them as a dictionary.
    """
    weights: dict[str, float] = {}

    # Core ETF weights (SPY, QQQ, and TQQQ for the leveraged variant)
    for sym, col in [("SPY", "target_spy_weight"), ("QQQ", "target_qqq_weight"), ("TQQQ", "target_tqqq_weight")]:
        w = float(signal.get(col, 0.0) or 0.0)
        if abs(w) > 1e-9:
            weights[sym] = w

    # Overlay stock weights (individual stock picks)
    overlay_raw = signal.get("overlay_weights_json", "{}")
    try:
        overlay = json.loads(str(overlay_raw)) if pd.notna(overlay_raw) else {}
    except Exception:
        overlay = {}

    for ticker, weight in overlay.items():
        ticker = str(ticker).upper().strip()
        w = float(weight)
        if abs(w) > 1e-9:
            weights[ticker] = weights.get(ticker, 0.0) + w

    return weights


def scale_weights(weights: dict[str, float], max_gross: float) -> dict[str, float]:
    """
    Scale weights down if total gross exposure exceeds the limit.

    PLAIN ENGLISH: If the strategy says to invest 125% of your money (using
    leverage), but you only want to invest 100%, this scales everything down
    proportionally.
    """
    gross = sum(abs(w) for w in weights.values())
    if gross <= max_gross + 1e-9 or gross <= 0:
        return dict(weights)
    scale = max_gross / gross
    return {t: w * scale for t, w in weights.items()}


# ─────────────────────────────────────────────────────────────────────────────
# ORDER GENERATION — compares target weights to current positions
# ─────────────────────────────────────────────────────────────────────────────

def generate_orders(
    broker: AlpacaBroker,
    target_weights: dict[str, float],
    force: bool = False,
) -> list[dict]:
    """
    Compare current positions to targets and generate buy/sell orders.

    PLAIN ENGLISH: Looks at what you currently own, compares it to what
    the strategy wants you to own, and figures out what to buy/sell.
    Only generates orders if the difference ("drift") is big enough to
    matter — avoids tiny trades that cost more than they're worth.
    """
    equity = broker.get_equity()
    positions = broker.get_position_map()

    # Get current prices for all relevant tickers
    all_tickers = sorted(set(target_weights.keys()) | set(positions.keys()))
    prices: dict[str, float] = {}
    skipped_tickers: list[str] = []
    for ticker in all_tickers:
        px = broker.get_last_price(ticker)
        if px > 0:
            prices[ticker] = px
        else:
            skipped_tickers.append(ticker)

    # Log any tickers that couldn't get a price
    if skipped_tickers:
        print(f"    ⚠ Skipped {len(skipped_tickers)} tickers (no price): "
              f"{', '.join(skipped_tickers)}")

    orders = []

    for ticker in all_tickers:
        target_w = target_weights.get(ticker, 0.0)
        px = prices.get(ticker, 0.0)
        if px <= 0:
            continue

        # Current weight = (shares × price) / equity
        current_qty = positions.get(ticker, 0)
        current_value = current_qty * px
        current_w = current_value / equity if equity > 0 else 0.0

        # Target shares
        target_value = target_w * equity
        target_qty = int(target_value / px)

        # Drift = difference between target and current weight
        drift = abs(target_w - current_w)

        # Skip if drift is below threshold (unless forced)
        threshold = ETF_DRIFT_THRESHOLD if ticker in ETF_TICKERS else OVERLAY_DRIFT_THRESHOLD
        if drift < threshold and not force:
            continue

        # How many shares to trade
        delta_qty = target_qty - current_qty
        if delta_qty == 0:
            continue

        # Skip tiny orders
        trade_value = abs(delta_qty * px)
        if trade_value < MIN_TRADE_VALUE:
            continue

        side = "buy" if delta_qty > 0 else "sell"
        orders.append({
            "ticker": ticker,
            "side": side,
            "quantity": abs(delta_qty),
            "price": px,
            "trade_value": trade_value,
            "current_weight": round(current_w, 4),
            "target_weight": round(target_w, 4),
            "drift": round(drift, 4),
            "current_qty": current_qty,
            "target_qty": target_qty,
        })

    # Sort: sells first (free up cash), then buys by size
    orders.sort(key=lambda o: (0 if o["side"] == "sell" else 1, -o["trade_value"]))
    return orders


# ─────────────────────────────────────────────────────────────────────────────
# PAPER TRADE LOG — records every submission for tracking performance
# ─────────────────────────────────────────────────────────────────────────────

def log_submission(orders: list[dict], order_ids: list[str]) -> None:
    """Save a record of submitted orders to the paper log file."""
    rows = []
    now = datetime.now(timezone.utc).isoformat()
    for order, oid in zip(orders, order_ids):
        rows.append({
            "submitted_at": now,
            "order_id": oid,
            "ticker": order["ticker"],
            "side": order["side"],
            "quantity": order["quantity"],
            "price": order["price"],
            "trade_value": order["trade_value"],
            "target_weight": order["target_weight"],
            "fill_status": "pending",
        })

    df = pd.DataFrame(rows)
    if PAPER_LOG_FILE.exists():
        existing = pd.read_csv(PAPER_LOG_FILE)
        df = pd.concat([existing, df], ignore_index=True)
    df.to_csv(PAPER_LOG_FILE, index=False)


def _already_submitted_today() -> bool:
    """
    Check if orders were already submitted today.

    PLAIN ENGLISH: Prevents double-ordering.  If you accidentally run
    --submit twice in one day, the second run will warn you instead of
    placing duplicate trades.
    """
    if not PAPER_LOG_FILE.exists():
        return False
    try:
        log = pd.read_csv(PAPER_LOG_FILE)
        if log.empty:
            return False
        # Check for submissions from today (UTC)
        ts_col = "submitted_at" if "submitted_at" in log.columns else "timestamp"
        if ts_col not in log.columns:
            return False
        dates = pd.to_datetime(log[ts_col], errors="coerce", utc=True)
        today = pd.Timestamp.now(tz="UTC").normalize()
        return bool((dates.dt.normalize() == today).any())
    except Exception:
        return False


# ─────────────────────────────────────────────────────────────────────────────
# EQUITY SNAPSHOT — saves account value for gauntlet tracking
# ─────────────────────────────────────────────────────────────────────────────

def snapshot_equity(broker: AlpacaBroker) -> None:
    """
    Save a snapshot of today's account equity to the tracking CSV.

    PLAIN ENGLISH: The gauntlet needs a history of your account value over
    time to compute Sharpe ratio and max drawdown.  This saves today's
    balance so the gauntlet has data to work with.  Runs automatically
    after every order submission.
    """
    try:
        equity = broker.get_equity()
        cash = broker.get_cash()
    except Exception as e:
        print(f"    ⚠ Could not snapshot equity: {e}")
        return

    now = datetime.now()
    row = {
        "date": now.strftime("%Y-%m-%d"),
        "timestamp": now.strftime("%Y-%m-%d %H:%M:%S"),
        "equity": round(equity, 2),
        "cash": round(cash, 2),
        "invested": round(equity - cash, 2),
    }

    df = pd.DataFrame([row])
    if EQUITY_FILE.exists():
        existing = pd.read_csv(EQUITY_FILE)
        # Don't duplicate same-day entries — keep latest
        existing["date"] = existing["date"].astype(str)
        existing = existing[existing["date"] != row["date"]]
        df = pd.concat([existing, df], ignore_index=True)

    df.to_csv(EQUITY_FILE, index=False)
    print(f"    ✓ Equity snapshot: ${equity:,.2f} → {EQUITY_FILE.name}")


# ─────────────────────────────────────────────────────────────────────────────
# ORDER RECONCILIATION — check if submitted orders actually filled
# ─────────────────────────────────────────────────────────────────────────────

def reconcile_orders(broker: AlpacaBroker) -> None:
    """
    Query Alpaca for order statuses and update the paper log.

    PLAIN ENGLISH: After you submit orders, this checks with Alpaca to see
    if they actually filled.  Updates the log CSV with the real status
    (filled, cancelled, partially_filled, etc.) so the gauntlet can
    compute accurate fill rates.
    """
    if not PAPER_LOG_FILE.exists():
        print("  No paper log found — nothing to reconcile.")
        return

    log = pd.read_csv(PAPER_LOG_FILE)
    if log.empty or "order_id" not in log.columns:
        print("  Paper log is empty or missing order_id column.")
        return

    # Only reconcile orders that are still pending
    if "fill_status" not in log.columns:
        log["fill_status"] = "pending"

    pending_mask = log["fill_status"].astype(str).str.lower().isin(["pending", ""])
    pending = log[pending_mask]

    if pending.empty:
        print("  All orders already reconciled — nothing to update.")
        return

    print(f"  Reconciling {len(pending)} pending orders...")
    updated = 0
    for idx, row in pending.iterrows():
        oid = str(row["order_id"])
        if oid.startswith("ERROR") or not oid:
            log.at[idx, "fill_status"] = "submission_failed"
            updated += 1
            continue
        try:
            order = broker._api.get_order(oid)
            status = str(order.status).lower()
            log.at[idx, "fill_status"] = status
            if hasattr(order, "filled_qty") and order.filled_qty:
                log.at[idx, "filled_qty"] = int(float(order.filled_qty))
            if hasattr(order, "filled_avg_price") and order.filled_avg_price:
                log.at[idx, "filled_avg_price"] = float(order.filled_avg_price)
            updated += 1
            status_icon = "✓" if status == "filled" else "⚠"
            print(f"    {status_icon} {row['ticker']} {row['side']} "
                  f"{int(row['quantity'])} → {status}")
        except Exception as e:
            log.at[idx, "fill_status"] = "query_failed"
            print(f"    ✗ {row['ticker']} order {oid[:12]}... → query failed: {e}")
            updated += 1

    log.to_csv(PAPER_LOG_FILE, index=False)
    print(f"\n  ✓ Reconciled {updated} orders. Log updated → {PAPER_LOG_FILE.name}")


# ─────────────────────────────────────────────────────────────────────────────
# MAIN — command line interface
# ─────────────────────────────────────────────────────────────────────────────

def print_account_status(broker: AlpacaBroker) -> None:
    """Print current account state."""
    equity = broker.get_equity()
    cash = broker.get_cash()
    positions = broker.get_positions()

    print(f"\n{'═'*60}")
    print(f"  ALPACA PAPER TRADING ACCOUNT")
    print(f"{'═'*60}")
    print(f"  Equity:     ${equity:,.2f}")
    print(f"  Cash:       ${cash:,.2f}")
    print(f"  Invested:   ${equity - cash:,.2f}")
    print(f"  Market:     {'OPEN ✓' if broker.is_market_open() else 'CLOSED ✗'}")
    print(f"{'─'*60}")

    if positions:
        print(f"  {'Ticker':<8s} {'Qty':>6s} {'Avg Price':>10s} {'Value':>12s} {'Weight':>8s}")
        print(f"  {'─'*50}")
        for p in sorted(positions, key=lambda x: -x.quantity * x.avg_price):
            value = p.quantity * p.avg_price
            weight = value / equity if equity > 0 else 0
            print(f"  {p.ticker:<8s} {p.quantity:>6d} ${p.avg_price:>9.2f} ${value:>11,.2f} {weight:>7.1%}")
        invested = sum(p.quantity * p.avg_price for p in positions)
        print(f"  {'─'*50}")
        print(f"  {'TOTAL':<8s} {'':>6s} {'':>10s} ${invested:>11,.2f} {invested/equity:>7.1%}")
    else:
        print("  No positions (100% cash)")
    print()


def print_order_plan(orders: list[dict]) -> None:
    """Print the proposed orders before submission."""
    if not orders:
        print("  No orders needed — portfolio is on target.")
        return

    total_buy = sum(o["trade_value"] for o in orders if o["side"] == "buy")
    total_sell = sum(o["trade_value"] for o in orders if o["side"] == "sell")

    print(f"\n  ORDER PLAN ({len(orders)} orders)")
    print(f"  {'─'*55}")
    print(f"  {'Action':<6s} {'Ticker':<8s} {'Qty':>6s} {'Price':>9s} {'Value':>10s} "
          f"{'Current':>8s} {'Target':>8s} {'Drift':>7s}")
    print(f"  {'─'*55}")

    for o in orders:
        action = "BUY" if o["side"] == "buy" else "SELL"
        print(f"  {action:<6s} {o['ticker']:<8s} {o['quantity']:>6d} "
              f"${o['price']:>8.2f} ${o['trade_value']:>9,.2f} "
              f"{o['current_weight']:>7.1%} {o['target_weight']:>7.1%} "
              f"{o['drift']:>6.1%}")

    print(f"  {'─'*55}")
    print(f"  Total buys:  ${total_buy:,.2f}")
    print(f"  Total sells: ${total_sell:,.2f}")
    print(f"  Net flow:    ${total_buy - total_sell:+,.2f}")
    print()


def main():
    parser = argparse.ArgumentParser(
        description="Alpaca paper trading for TQQQ-enhanced core-satellite strategy"
    )
    parser.add_argument("--submit", action="store_true",
                        help="Actually submit orders (default: just show plan)")
    parser.add_argument("--status", action="store_true",
                        help="Just show account status, no order planning")
    parser.add_argument("--reconcile", action="store_true",
                        help="Check if pending orders filled and update log")
    parser.add_argument("--force", action="store_true",
                        help="Skip drift thresholds AND duplicate-day check")
    parser.add_argument("--market-order", action="store_true", default=True,
                        help="Use market orders (default)")
    args = parser.parse_args()

    # ── Connect to Alpaca ───────────────────────────────────────────────
    try:
        broker = AlpacaBroker()
        print("  ✓ Connected to Alpaca paper trading")
    except ImportError as e:
        print(f"  ✗ {e}")
        sys.exit(1)
    except ValueError as e:
        print(f"  ✗ {e}")
        sys.exit(1)
    except ConnectionError as e:
        print(f"  ✗ {e}")
        sys.exit(1)

    # ── Show account status ─────────────────────────────────────────────
    print_account_status(broker)

    if args.status:
        return

    # ── Reconcile mode: check fill statuses of pending orders ──────────
    if args.reconcile:
        reconcile_orders(broker)
        return

    # ── Load strategy signal ────────────────────────────────────────────
    try:
        signal = load_signal()
        print(f"  ✓ Signal loaded (predicted_at: {signal.get('predicted_at', 'unknown')})")
        print(f"    Strategy: {signal.get('paper_signal_type', 'unknown')}")
        print(f"    Regime:   {signal.get('current_regime', 'unknown')}")
        print(f"    Gross:    {signal.get('gross_exposure', 'unknown')}")
    except (FileNotFoundError, RuntimeError) as e:
        print(f"  ✗ {e}")
        sys.exit(1)

    # ── Parse and scale target weights ──────────────────────────────────
    raw_weights = parse_target_weights(signal)
    target_weights = scale_weights(raw_weights, MAX_GROSS_EXPOSURE)

    raw_gross = sum(abs(w) for w in raw_weights.values())
    scaled_gross = sum(abs(w) for w in target_weights.values())
    if abs(raw_gross - scaled_gross) > 0.01:
        print(f"    Scaled {raw_gross:.2f}x → {scaled_gross:.2f}x "
              f"(max gross = {MAX_GROSS_EXPOSURE:.2f}x)")

    print(f"\n  TARGET ALLOCATION")
    print(f"  {'─'*40}")
    for ticker, w in sorted(target_weights.items(), key=lambda x: -abs(x[1])):
        label = "ETF" if ticker in ETF_TICKERS else "Stock"
        print(f"  {ticker:<8s} {w:>7.1%}  ({label})")
    print(f"  {'─'*40}")
    print(f"  Gross exposure: {scaled_gross:.2%}")

    # ── Generate orders ─────────────────────────────────────────────────
    print("\n  Comparing to current positions...")
    orders = generate_orders(broker, target_weights, force=args.force)
    print_order_plan(orders)

    if not orders:
        return

    # ── Submit orders ───────────────────────────────────────────────────
    if not args.submit:
        print("  ⚠  DRY RUN — orders NOT submitted. Use --submit to execute.")
        return

    # Duplicate submission check — prevents running --submit twice in one day
    if _already_submitted_today() and not args.force:
        print("  ⚠  Orders already submitted today. Use --force to override.")
        print(f"     Check log: {PAPER_LOG_FILE}")
        return

    if not broker.is_market_open():
        print("  ⚠  Market is CLOSED. Orders will queue for next open.")
        resp = input("  Continue anyway? [y/N]: ").strip().lower()
        if resp != "y":
            print("  Aborted.")
            return

    print(f"\n  Submitting {len(orders)} orders...")
    order_ids = []
    for o in orders:
        try:
            order = Order(
                ticker=o["ticker"],
                side=o["side"],
                quantity=o["quantity"],
                type="market",
            )
            oid = broker.place_order(order)
            order_ids.append(oid)
            print(f"    ✓ {o['side'].upper()} {o['quantity']} {o['ticker']} "
                  f"→ order_id={oid[:12]}...")
        except Exception as e:
            order_ids.append(f"ERROR: {e}")
            print(f"    ✗ {o['side'].upper()} {o['quantity']} {o['ticker']} "
                  f"FAILED: {e}")

    # ── Log the submission ──────────────────────────────────────────────
    log_submission(orders, order_ids)
    print(f"\n  ✓ {len(orders)} orders submitted. Log saved → {PAPER_LOG_FILE}")

    # ── Auto-snapshot equity for gauntlet tracking ─────────────────────
    # PLAIN ENGLISH: Saves today's account value so the gauntlet can
    # compute your Sharpe ratio and drawdown over time.  Happens
    # automatically — no need to run a separate command.
    snapshot_equity(broker)

    print(f"    Check fills: python3 alpaca_paper_trading.py --reconcile")


if __name__ == "__main__":
    main()
